project:
  type: website

website:
  title: "fastqc-viz"
  search: false
  favicon: favicon.svg

sidebar: false

format:
  html:
    self-contained: true
    theme: cosmo
    css: styles.css
    toc: true
  